### ISSUE TITLE
Link to forked lab doesn't work

### ISSUE THREAD

**Issue by NColey** [learn-co-curriculum/advanced-hashes-hashketball#15]
When I clicked on the link for "You forked this lab" to make my pull request it took me to a 'Page not found' GitHub page. I believe this is because the link goes to https://github.com/NColey/hashketball-web-0915 when it should go to https://github.com/NColey/advanced-hashes-hashketball-web-0915. I'm guessing the link title was changed at some point but if they could be all updated to match that would make things easier. Thanks!

**Comment by deniznida** [comment]
Thanks @NColey for opening this issue. Our labs team is working on it.
