### ISSUE TITLE
Doesn't link correctly with checks on lesson

### ISSUE THREAD

**Issue by chintas1** [learn-co-curriculum/advanced-hashes-hashketball#21]
The links for the tests pass check and pull request check on the lesson page are incorrect. Despite passing all the tests and submitting the pull request on nitrous the lights don't trigger (tried multiple times, restarting, waiting two days, ect..). Another student also had the same issue and I think it might have something to do with this: https://github.com/learn-co-curriculum/advanced-hashes-hashketball/issues/15.

**Comment by AnnJohn** [comment]
Hi @chintas1 this is most likely still a bug that's occurring. Could you please file a bug report? If you hover over your profile pic in Learn, you'll see an option to Report a Bug. Thanks!
