### ISSUE TITLE
Hashketball Lights Not Turning Green

### ISSUE THREAD

**Issue by imac18078** [learn-co-curriculum/advanced-hashes-hashketball#22]
When I fork the hashketball lab from the learn.co webpage, it goes to the hashketball-001-prework-web repository. I completed all the challenges and got them to pass. However, none of the lights turn green. I figured out that the learn.co green lights are linked to a different repository: advanced-hashes-hashketball-001-prework-web. I managed to fork the lab to this different repo and also do a pull request on github (getting both those lights to turn green), but still can't figure out how to run the rspec test suite in github in the advanced-hashes repo. any help or suggestions would be greatly appreciated! thanks!

**Comment by AnnJohn** [comment]
Hi @imac18078 this looks like it's a bug, so could you file a bug report? If you hover over your profile pic in Learn, you'll see an option to Report a Bug. Thanks!
