### ISSUE TITLE
Incorrectly refers to `:num_points_scored` rspec wants `:points` and `#num_points_scored`

### ISSUE THREAD

**Issue by fossbender** [learn-co-curriculum/advanced-hashes-hashketball#23]
Several places the `README` refers to `:num_points_scored` as one of the keys for the player hash. But `rspec` requires `:points` to be the key. There is a `#num_points_scored` method, and that is fine as-is. (Only mentioning this because a find/replace could overwrite the correct method name.)

**Comment by ipc103** [comment]
fixed by 9904fd4
