### ISSUE TITLE
Discrepancy between the Spec and the readme

### ISSUE THREAD

**Issue by sev2109** [learn-co-curriculum/advanced-hashes-hashketball#24]
There is a discrepancy in this lab between the keys that the readme states we should use in constructing the hash, and the keys that the spec file uses. In the readme, the key :num_points_scored is used, while in the spec, the key :points is used. This makes it impossible to pass the player_stats method's test without changing the entire hash (or the spec). Thanks!

**Comment by ipc103** [comment]
fixed by 9904fd4
