### ISSUE TITLE
clarity of instructions for hash construction

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/advanced-hashes-hashketball#35]
This sentence is a bit unclear: "The :players key points to a hash of players whose names (as strings) are the keys to a hash containing their stats."

The solution code reflects:

      players: [
        {
          player_name: "Alan Anderson",
          number: 0,
          shoe: 16,
          points: 22,
          rebounds: 12,
          assists: 12,
          steals: 3,
          blocks: 1,
          slam_dunks: 1
        },

which has player_name as a key of the actual name value in string format. Also, players is an array.

**Comment by realAndrewCohn** [comment]
Hello! The solution code has been updated to reflect the changes in the readme: https://github.com/learn-co-curriculum/advanced-hashes-hashketball/blob/solution/hashketball.rb
