### ISSUE TITLE
Make #big_shoe_rebound a bit harder?

### ISSUE THREAD

**Issue by maxcell** [learn-co-curriculum/advanced-hashes-hashketball#38]
In order to make sure the student is truly understanding the lesson that this method is trying to do, do we think it may be better to assign a value deeper into the hash?

https://github.com/learn-co-curriculum/advanced-hashes-hashketball/blob/d604a0a5db28745c0f85fa69f42e2ebed862d5fe/spec/hashketball_spec.rb#L239-L245

**Comment by sgharms** [comment]
@maxcell We're going to revisit this as part of other internal projects. I'm going to close but a revamp of this lesson has already come and another is coming!
