### ISSUE TITLE
Code is prepopulated

### ISSUE THREAD

**Issue by annaconaway19** [learn-co-curriculum/advanced-hashes-hashketball#40]
When I forked this lab, the hasketball.rb file was already prepopulated with the complete passing code. I was able to read through and understand the methods but the instructions are to build it ourselves so I'm not sure if this is correct.

**Comment by maxwellbenton** [comment]
Hi @annaconaway19,

Thank you for providing this feedback. I was not able to reproduce this issue but we have recently updated these materials and can confirm that the `hasketball.rb` does not currently have any solution code present in the file.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
