### ISSUE TITLE
Old link to "Codecademy - A Night at the Movies" doesn't exist

### ISSUE THREAD

**Issue by YevgeniySob** [learn-co-curriculum/advanced-hashes-hashketball#42]
It redirects to
https://www.codecademy.com/catalog/subject/all 

instead of  
http://external.codecademy.com/courses/ruby-beginner-en-0i8v1/0/1

**Comment by maxwellbenton** [comment]
Hi @YevgeniySob,

Thanks for letting us know! This link has been removed.
