### ISSUE TITLE
Player Names & stats differ on the readme.md vs what is on the learn.co website causing tests to fail

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/advanced-hashes-hashketball#48]
**Description**
I found this issue when doing the Hashketball lab.  I used the Learn.co website to fill in the stats into my hash.  Upon getting my num_points_scored method working, I noticed that when I ran the tests for it, I got a failure for a player of "Kemba Walker"

`Failures:
  1) hashketball #num_points_scored knows the number of points scored by each player
     Failure/Error: expect(num_points_scored("Kemba Walker")).to eq(6)
       expected: 6
            got: nil
       (compared using ==)
      ./spec/hashketball_spec.rb:33:in block (3 levels) in <top (required)>`

I double checked on the learn.co website tables for the teams and didn't find "Kemba Walker"
![image](https://user-images.githubusercontent.com/39208179/58821104-98e0e980-85f1-11e9-8180-85262add1996.png)

I then looked at the README.md file in my IDE (Learn IDE 3) and found that "Ben Haywood" had been replaced with "Kemba Walker" in the roster for the Away team.  

**Expected Results**
The rspec tests would have searched for "Ben Haywood" instead of Kemba Walker OR the learn.co web version of the lab would have "Kemba Walker" instead of "Ben Haywood". 

**Actual Results**
The last player on the Away team is inconsistent between the learn.co web platform and the tests & readme file in the IDE.  The learn.co web version of the lab explanation should have "Kemba Walker" as the last player (OR the tests and the readme in the IDE should replace Kemba Walker with Ben Haywood.) 

This is discrepancy of data is also affecting the Bismack Biyombo test for the #player_stats method as well: 
![image](https://user-images.githubusercontent.com/39208179/58824158-ab125600-85f8-11e9-816b-b9842f20f554.png)
![image](https://user-images.githubusercontent.com/39208179/58824262-e44ac600-85f8-11e9-95d3-f21c7a4894c5.png)

And the Kemba Walker test for the #player_stats method too:
![image](https://user-images.githubusercontent.com/39208179/58824519-78b52880-85f9-11e9-85f6-3cd6ee6dfd2b.png)

![image](https://user-images.githubusercontent.com/39208179/58824492-6b983980-85f9-11e9-91a1-5ca25f2b9c2d.png)

**Comment by sgharms** [comment]
This seems to be a snag in our deployment. We'll adjust. Thanks.

**Comment by maxwellbenton** [comment]
Hi @jrodden1,

This lab was updated recently to resolve some open issues and for some reason, you were able to fork the newer content but were still viewing the outdated lesson materials Learn.co. I was, unfortunately, unable to recreate the experience you had. 

However, I am able to confirm that the updated lesson content is now correctly showing up in Learn.co for your cohort/batch so students currently working on this lab should see the correct player stats in the Learn.co aligning with the forked tests.

We apologize for any frustration you might have encountered during this process but thank you for helping us identify an issue in our deployment that we are reviewing further.

If you do not believe that this issue has been addressed or are still experiencing this problem, please re-open this issue. 💙
