### ISSUE TITLE
YouTube link removed

### ISSUE THREAD

**Issue by btbacker** [learn-co-curriculum/advanced-hashes-hashketball#55]
Video Walkthrough has been removed by uploader

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
